version: '3.8'

services:
  backend-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cpjs-api
    ports:
      - "5000:8080"
    restart: unless-stopped
    environment:
      - ASPNETCORE_URLS=http://+:8080
